### ISSUE TITLE
Run failure because of a dependency (`semver`) has removed functions

### ISSUE THREAD

**Issue by dilawar** [COVID-IWG/epimargin#122]
```sh
[centos@ip-172-26-6-166 karnataka (joss_lint_errors)]$ python3 age_rt.py 
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
Traceback (most recent call last):
  File "/home/centos/Work/FORKES/epimargin/studies/karnataka/age_rt.py", line 3, in <module>
    from epimargin.estimators import analytical_MPVS
  File "/home/centos/Work/FORKES/epimargin/epimargin/estimators.py", line 7, in <module>
    import pymc3 as pm
  File "/home/centos/.local/lib/python3.9/site-packages/pymc3-3.11.2-py3.9.egg/pymc3/__init__.py", line 34, in <module>
    if not semver.match(theano.__version__, ">=1.1.2"):
AttributeError: module 'semver' has no attribute 'match'
```

The package `semver` has deprecated/removed the `match` function (https://github.com/python-semver/python-semver/issues/236).

**Comment by dilawar** [comment]
This has been patched in `pymc3`(https://github.com/pymc-devs/pymc3/issues/4546).

**Comment by dilawar** [comment]
pinning `semver==2.12.0` fixed the issue. It is related to upstream.
